import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Home from "./page";
// import { QueryProvider } from "next-graphql-react"; // by using this we dont have to create a seperate component for QueryProvider just import it from the package(npm i next-graphql-react)and wrap the children in it .
import QueryProvider from "@/components/QueryProvider";
import Navbar from "@/components/navbar"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

         <QueryProvider>
          {/* Navbar is now included in the layout */}
          <div className="sticky top-0 z-50 bg-white shadow-md text-black text-center">
            <Navbar />
          </div>
          <div className="min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
            {children}
          </div>
        </QueryProvider>
         {/* <QueryProvider>
          <Navbar/>
          {children}
          </QueryProvider> */}

      </body>
    </html>
  );
}
